### ISSUE TITLE
Hide empty fields

### ISSUE THREAD

**Issue by arteteco** [FriendsOfFlarum/masquerade#58]
Hello everyone,
well, as I wrote, especially for the fields displayed under the user bio would be nice to be able to hide the empty ones

Thanks

**Comment by clarkwinkelmann** [comment]
I'm not sure I understand what you're asking.

By default fields are visible in the user's Masquerade tab.

When "show in bio" is enabled, the field is ALSO shown on the user card.

I don't think there is currently any logic to show/hide fields that have been filled or not.

**Comment by arteteco** [comment]
I'm asking to add the feature to hide empty fields, they look especially bad under the bio

Sorry if that part gave you some confusion in understanding the issue, actually it wasn't necessary!

**Comment by rafaucau** [comment]
@clarkwinkelmann It looks bad on a user's profile when someone browses their profile and sees a bunch of blank fields.
![image](https://user-images.githubusercontent.com/25438601/114270046-7a788000-9a0a-11eb-995b-4492dcdffc68.png)

**Comment by clarkwinkelmann** [comment]
No choice has been made on how to handle this issue so far.

I think my preferred solution would be to apply a className to the fields so that forum owners can customize how empty fields should look like visually, by either adding "Empty" text in pseudo-elements, or hiding the field completely.

If we start adding options to customize the look, I fear we won't know where to stop. If we add an option for this, there will be requests for other customization, and where should we stop. Likewise it would be nice to be able to customize vertical vs horizontal layout for labels+value, but I feel like it might be too much to have that as an option and would be better for custom CSS.

The UI is pretty poor by default, so I wouldn't be against a new default design (CSS, but might also require changes to markup) to give it a more engaging look.

In any case I don't think we should force hiding the fields as some people will want to show empty fields.
