### ISSUE TITLE
Redirect the user home after completing their profile

### ISSUE THREAD

**Issue by franga2000** [FriendsOfFlarum/masquerade#60]
When a user is forced to complete their profile and they do so, it is unclear to them if they were successful or how to continue to the forum if they were.

### Setup

Flarum beta 14, extension at `0.3.6`, *"Force users to complete profile"* = `true`

### Steps to reproduce

**1. A user signs up**  
They are redirected to `/masquerade/configure` and shown a yellow warning to fill out their profile  
**2. They fill out the form and press Save**
**BUG:** the yellow warning doesn't go away (since the page isn't actually refreshed) - user doesn't know they were successful  
**CONFUSION:** the user (being new to the forum) doesn't know where to go next *(it's amazing how many people don't know that the navbar title is usually a link to the home page)*

### Proposed solutions

Obviously, making the warning go away after the profile is complete is the first step.  
To address the new user confusion part, I see two possibilities:

1. Redirect the user to the front page (or a configurable location?)
2. Display a success message (where the warning was) along the lines of *"Your profile is now complete! You may [continue to the forum](#)"* (the link taking them to the front page)

I'm personally leaning more towards (2) as it seems a bit less "rigid" if that makes sense, but perhaps (1) could also be implemented as a configurable option on top of (2) for those that want it.

Thoughts? (I need this for my forum, so I can implement it myself, unless someone more familiar with the codebase can spare the time :sweat_smile:)

**Comment by clarkwinkelmann** [comment]
Makes sense.

That feature is such a hack, I'm not even sure what would make more sense.

Technically, the user can always navigate away from the form, and nothing prevents them from interacting with the forum. So there's not really such a thing as "required", more like "strong and annoying forced redirect".

What we could do is trigger a full page redraw if the warning is present and the profile was submitted.

I would say it makes sense to redirect to the homepage after a forced completion, but I also think the button should reflect that as to not confuse the user, like a button saying "Save and continue to forum". Maybe even show that new button next to existing button, so that the user gets the choice.

If you would like to submit a PR, that's welcome! Otherwise I might be able to add that when I work on the beta 15 update in 1 or 2 weeks.

**Comment by ctml91** [comment]
This is a big one for me. I had to disable all obligatory fields because users were confused after being left on their profile, especially since there is no back navigation button if you're taken directly to your profile page (core issue, I think)

**Comment by clarkwinkelmann** [comment]
This is how it will look like in version 0.3.7 if you save while the yellow banner is visible.

![image](https://user-images.githubusercontent.com/5264300/108005321-a7a34600-6ff8-11eb-9c6d-c548c735c460.png)
